### ISSUE TITLE
README错误

### ISSUE THREAD

**Issue by Jerry-Z07** [Funny1Potato/nonebot-plugin-sendpic#1]
在README中的这一段：
四个配置项均以列表形式填写，并 严格一一对应，例：

pic_num = [8,4,6]
pic_tag = ["御姐","","萝莉|金发"]
pic_time = ["0-18-00-00","0-08-00-00","1-00-00-30"]
pin_group = ["123456789","1145141919","123456789"]

此处pin_group应为pic_group

**Comment by Funny1Potato** [comment]
多谢提醒，已修改
