### ISSUE TITLE
提前结束，无法正常发图

### ISSUE THREAD

**Issue by Jerry-Z07** [Funny1Potato/nonebot-plugin-sendpic#2]
Ubuntu 22.04 
nb 2.3 
部署后已经正常使用了一段时间，但最近开始出现无法发图的情况，已确认网络环境正常 
似乎在发图前提前结束了 
以下为输出
![image](https://github.com/user-attachments/assets/ee7b9aa6-5fb1-42c6-b4d4-6f730ac611d3)

**Comment by Funny1Potato** [comment]
请问在提供关键词搜索以及发送多张图的时候是否也会有这样的问题？

**Comment by Funny1Potato** [comment]
请尝试将插件更新至0.1.1版本

**Comment by Jerry-Z07** [comment]
更新至0.1.1后已恢复正常
